---
# tasks file for certbot

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: install certbot
  ansible.builtin.pip:
    name: "{{ certbot_pip_packages }}"
    state: present

- name: Creating secrets file
  copy:
    dest: "tmp/credentials.ini"
    content: |
      certbot_dns_cpanel:cpanel_url = {{ lookup('bitwarden', 'certbot-dns-cpanel', field='uri') }}
      certbot_dns_cpanel:cpanel_username = {{ lookup('bitwarden', 'certbot-dns-cpanel', field='username') }}
      certbot_dns_cpanel:cpanel_token = {{ lookup('bitwarden', 'certbot-dns-cpanel', field='password') }}

- name: get and install certificates (Standalone)
  ansible.builtin.command:
    cmd: |
      certbot certonly --noninteractive
      --{{ certbot_system }}
      --domain {{ certbot_domains | join(',') }}
      --agree-tos
      --email {{ certbot_email }}
      --authenticator certbot-dns-cpanel:cpanel
      --certbot-dns-cpanel:cpanel-credentials /tmp/credentials.ini
    creates: /etc/letsencrypt/accounts
  when:
    - certbot_ci_mode is not defined
    - certbot_system == "standalone"

- name: get and install certificates (Managed)
  ansible.builtin.command:
    cmd: |
      certbot --noninteractive
      --{{ certbot_system }}
      --domain {{ certbot_domains | join(',') }}
      --agree-tos
      --email {{ certbot_email }}
      --no-redirect
    creates: /etc/letsencrypt/accounts
  when:
    - certbot_ci_mode is not defined
    - certbot_system != "standalone"

- name: set up automatic renewal
  ansible.builtin.cron:
    name: certbot
    minute: "16"
    hour: "2,14"
    job: "/usr/bin/certbot renew -q"
  notify:
    - restart certbot_system
