---
# tasks file for certbot
- name: install system packges
  ansible.builtin.package:
    name: "{{ certbot_packages }}"
    state: present

- name: install pip packges
  ansible.builtin.pip:
    name: "{{ certbot_pip_packages }}"
    state: present

- name: Creating secrets file
  copy:
    dest: "/etc/letsencrypt/credentials.ini"
    content: |
      certbot_dns_cpanel:cpanel_url = {{ cpanel_url }}
      certbot_dns_cpanel:cpanel_username = {{ cpanel_username }}
      certbot_dns_cpanel:cpanel_token = {{ cpanel_token }}

- name: get and install certificates (Standalone)
  ansible.builtin.command:
    cmd: |
      certbot certonly --noninteractive
      --domain {{ certbot_domains | join(',') }}
      --agree-tos
      --email {{ certbot_email }}
      --authenticator certbot-dns-cpanel:cpanel
      --certbot-dns-cpanel:cpanel-credentials /etc/letsencrypt/credentials.ini
    creates: /etc/letsencrypt/accounts

- name: set up automatic renewal
  ansible.builtin.cron:
    name: certbot
    minute: "16"
    hour: "2,14"
    job: "/usr/bin/certbot renew -q"

